---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tester

<!-- badges: start -->
<!-- badges: end -->

The goal of tester is to establish a coherent workflow for building R-packages.  The `tester` package itself is best used as a doormat to the home that the R-community built.

## Installation

You can install the released version of tester from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("tester")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("threadingdata/tester")
```

# Basic examples

```{r example}
library(tester)
## basic example code
```

## Say Hello!

```{r hello}
hello('you spawn of Satan')
```

## Say Goodbye!

```{r goodbye}
goodbye('you filthy animal')
```

## Say Hello & Goodbye!

```{r hello_goodbye}
hello_goodbye('get off my lawn')
```
